schema_version = 1

project {
  # This repository is not open source.
  license        = "MPL-2.0"
  copyright_year = 2020

  # The documentation claims this is the default, but it's not.
  copyright_holder = "IBM Corp."

  # (OPTIONAL) A list of globs that should not have copyright/license headers.
  # Supports doublestar glob patterns for more flexibility in defining which
  # files or folders should be ignored
  header_ignore = [
    # Ignored because they are machine generated by tooling that can't
    # embed copywrite information. Adding copywrite headers would just
    # confuse the tooling.
    "pnpm-lock.yaml",

    # Examples:
    # "vendor/**",
    # "**autogen**",
  ]
}
