# Copyright IBM Corp. 2020, 2026
# SPDX-License-Identifier: MPL-2.0

packages:
  - docs
  - lineal-viz

autoInstallPeers: true

dedupeInjectedDeps: true

dedupePeerDependents: true

injectWorkspacePackages: true

onlyBuiltDependencies:
  - core-js
  - esbuild

publicHoistPattern:
  - ember-source

resolutionMode: highest

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: install
