packages:
  - .
  - docs

allowBuilds:
  esbuild: true
  core-js: false

autoInstallPeers: true

dedupeInjectedDeps: true

dedupePeerDependents: true

injectWorkspacePackages: true

publicHoistPattern:
  - ember-source

resolutionMode: highest

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: install
